# Generated by Django 3.0 on 2022-11-29 16:31

from django.db import migrations


def migrate_lettings(apps, schema_editor):
    old_table = apps.get_model('oc_lettings_site', 'Letting')
    new_table = apps.get_model('lettings', 'Letting')

    objs = list()

    fields = ('title', 'address_id')

    for data in old_table.objects.all():
        title = data.title
        address_id = data.address_id
        letting = new_table(title=title, address_id=address_id)
        objs.append(letting)

    new_table.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20221129_1655'),
    ]

    operations = [
        migrations.RunPython(migrate_lettings, migrations.RunPython.noop),
    ]
